// Common teaching languages for the connect wizard / channel settings picker.
// Plain English names — the chosen value goes straight into AI prompts as the
// authoritative target language (see teachers.target_language), so no codes.
// The picker is a datalist, so anything not listed can still be typed freely.
export const LANGUAGES = [
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'English',
  'Dutch',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Icelandic',
  'Irish',
  'Welsh',
  'Scottish Gaelic',
  'Breton',
  'Basque',
  'Catalan',
  'Galician',
  'Polish',
  'Czech',
  'Slovak',
  'Hungarian',
  'Romanian',
  'Bulgarian',
  'Croatian',
  'Serbian',
  'Slovenian',
  'Ukrainian',
  'Russian',
  'Lithuanian',
  'Latvian',
  'Estonian',
  'Greek',
  'Albanian',
  'Turkish',
  'Arabic',
  'Hebrew',
  'Persian',
  'Hindi',
  'Urdu',
  'Bengali',
  'Punjabi',
  'Tamil',
  'Telugu',
  'Mandarin Chinese',
  'Cantonese',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Tagalog',
  'Swahili',
  'Zulu',
  'Xhosa',
  'Afrikaans',
  'Yoruba',
  'Hausa',
  'Amharic',
  'Esperanto',
];
